### ISSUE TITLE
[Help] Can not upload dmg-file from macos to release

### ISSUE THREAD

**Issue by Griefed** [flying-ufo/action-upload-artifacts-and-release#3]
Hello there,

I am having trouble uploading a ~240mb .dmg-file asset to a release from withing a macos-step.
The error I am encountering is as follows:

```
Run nanoufo/action-upload-artifacts-and-release-assets@v1.5
  with:
    path: serverpackcreator-app/build/dist/ServerPackCreator-Installer-MacOS-4.0.0-alpha.7.dmg
  
    if-no-files-found: warn
    upload-release-files: true
    release-upload-url: https://uploads.github.com/repos/Griefed/ServerPackCreator/releases/88[2](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:2)1861[3](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:3)/assets{?name,label}
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.5-8/x6[4](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:4)
    JAVA_HOME_17_X64: /Users/runner/hostedtoolcache/Java_Zulu_jdk/17.0.[5](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:5)-8/x[6](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:6)4
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    GITHUB_TOKEN: ***
/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:18413
    throw error;
    ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:25823:26)
    at osName (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:28942:18)
    at getUserAgent (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:1840[7](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:7):53)
    at parseOptions (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:1[8](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:8)300:57)
    at new Octokit (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:18180:31)
    at Object.5438 (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:2160:28)
    at __nccwpck_require__ (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:32822:43)
    at /Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:32[9](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:9)95:14
    at /Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:33[11](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:11)8:3
    at Object.<anonymous> (/Users/runner/work/_actions/nanoufo/action-upload-artifacts-and-release-assets/v1.5/dist/index.js:33[12](https://github.com/Griefed/ServerPackCreator/actions/runs/3863780148/jobs/6586251730#step:14:12)1:12)
```

I could already confirm that the file exists. Interestingly, two other steps, one running on windows and one on ubuntu, upload the asset just fine, it is just the macos-step which runs into this particular error.

I was wondering whether anyone would be able to point me into a direction so I can correct what I did wrong in the configuration:

```yaml
# Does not work
      - name: Upload Mac Installer
        if: matrix.os == 'macos-latest'
        id: upload-release-asset-macos
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: |
            serverpackcreator-app/build/dist/ServerPackCreator-Installer-MacOS-${{ needs.prerelease.outputs.newtag }}.dmg
          if-no-files-found: warn
          upload-release-files: true
          release-upload-url: ${{ needs.prerelease.outputs.uploadurl }}

# Works just fine
      - name: Upload Windows Installer
        if: matrix.os == 'windows-latest'
        id: upload-release-asset-windows
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: |
            serverpackcreator-app/build/dist/ServerPackCreator-Installer-Windows-${{ needs.prerelease.outputs.newtag }}.msi
          if-no-files-found: warn
          upload-release-files: true
          release-upload-url: ${{ needs.prerelease.outputs.uploadurl }}

# Works just fine
      - name: Upload Ubuntu Installer
        if: matrix.os == 'ubuntu-latest'
        id: upload-release-asset-ubuntu
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: |
            serverpackcreator-app/build/dist/ServerPackCreator-Installer-Ubuntu-${{ needs.prerelease.outputs.newtag }}-amd64.deb
          if-no-files-found: warn
          upload-release-files: true
          release-upload-url: ${{ needs.prerelease.outputs.uploadurl }}
```

From what I could gather, the individual filesize for release-assets is 1000mb, which the macos file does not exceed. There's also no limitation on file-types which would affect this particular scenario.

If anyone can help me out here, it would be greatly appreciated.

Cheers,
Griefed
